### ISSUE TITLE
Duvidas sobre campos: código empresa e numero remessa 

### ISSUE THREAD

**Issue by jonyw4** [thiagohenrique0810/GARB-Gerador-de-Arquivos-de-Remessa-Bradesco#3]
Estou implementando o GARB em minha empresa e estou com uma duvida quanto aos campos:

### 'codigo_empresa'
Onde eu consigo esse código?

### 'numero_remessa'
Como proceder com esse numero? Visto que eu nunca fiz nenhuma remessa para o banco, como que funciona?

Aproveitando a oportunidade eu tenho outras duvidas:
Como faço para testar o código ou validar?
Qual é o procedimento para enviar a remessa? Eu envio depois que os boletos foram gerados no fim do dia?

Fico no aguardo das respostas! Muito obrigado. Espero no futuro poder colaborar com o projeto já que praticamente não encontrei nenhum parecido

**Comment by thiagohenrique0810** [comment]
O campo codigo_empresa é um código único que cada conta bancaria possui, você deve entrar em contato com o Bradesco netempresas para solicita-lo. Ele é necessário pois identifica sua conta na remessa, é um campo obrigatório.

O campo numero_remessa também é um numero único sequencial que informa em qual sequencial se encontra a remessa, você também deverá entrar em contato com o banco para solicita-lo. É semelhante a uma chave primaria de uma tabela, ele deverá ser armazenado, cada nova remessa terá um novo sequencial de numero de remessa. 
Ex.: 00001, 00002, 00003, ...

**Comment by jonyw4** [comment]
Ok @thiagohenrique0810, irei entrar em contato com o banco. Seria interessante você colocar isso lá no README para os próximos usuários fazerem isso e também no arquivo de teste, informando mais detalhes desse campo

E sobre essas outras dúvidas, você consegue me ajudar?:

- Como faço para testar o código ou validar?
- Qual é o procedimento para enviar a remessa? Eu envio depois que os boletos foram gerados no fim do dia?

Obrigado pelo feedback

**Comment by thiagohenrique0810** [comment]
falo sobre isso na descrição do projeto
